server: 
  port: 8889 
spring:
  profiles: dev
  application: 
    name: config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/
info:
  my:
    name: 时光
    message: 测试局部刷新机制
